### PR TITLE
Round up the list of contributors.

### LINKED ISSUE #89: sort out license text
Put all the license things where they go.

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
Fixes #89.

As before, I need signoffs from those listed. I used real names based on what's listed in your Github profiles; if you want to be differently credited, let me know.

Please affirm that you are okay with your contributions to Typhon being licensed under Apache 2:
* @washort 
* @markrwilliams 
* @edunham 
* @mythmon 
* @Julian 
* @dckc

### CODE REVIEW

**Comment by Julian** [comment]
Yes.

**Comment by mythmon** [comment]
:+1:

**Comment by edunham** [comment]
:+1:

**Comment by dckc** [comment]
yes. Apache 2

**Comment by markrwilliams** [comment]
i'm good with the license and my credit in the AUTHORS file. thanks!

**Comment by washort** [comment]
:+1: yes let's do it

**Pull request merged**
